name: make-release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building
        uses: .github/actions/build

      - uses: actions/upload-artifact@v2
        with:
          name: build-binary
          path: build/bin

  release:
    runs-on: windows-2019
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-binary
          path: build/bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            build/bin/hello.exe
          generate_release_notes: true
