name: make-release

on:
  push:
    # tags:
      # - "v*"

jobs:

  release_pre:
    runs-on: windows-2019
    # needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  release:
    runs-on: windows-2019
    # needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  # #     - name: call build

  #     - name: Build
  #       run: echo ${{ github.sha }} > Release.txt

  #     - name: Test
  #       run: cat Release.txt

  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           Release.txt
  #           build/bin/hello.exe
  #         generate_release_notes: true
