name: release

on:
  push:
    # tags:
      # - "v*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: 'shangchiwu/github-action-setup-msys2-test/.github/workflows/build-windows.yml@v0.0.3'

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            build/bin/hello.exe
          generate_release_notes: true
